#In production mode, a specific version of the image should be used for stability and security reasons.
version: '3'
services:
  db:
    image: 'mysql:8.1'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USERNAME}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "3306:3306"
