spring:
  application:
    name: student-result-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/srms
    username: srms
    password: secret
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 10000
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/srms
    driver-class-name: com.mysql.cj.jdbc.Driver
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
server:
  port: 8080
logging:
  level:
    root: info
    sql: info
    web: info

