spring:
  application:
    name: student-result-management-system
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      max-lifetime: ${HIKARI_MAX_LIFETIME}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
  jpa:
    open-in-view: false
  data:
    redis:
      password: ${APP_REDIS_PASSWORD}
      host: ${APP_REDIS_HOST}
server:
  port: 8080

