spring:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    hikari:
      minimum-idle: ${HIKARI_MINIMUM_IDLE}
      maximum-pool-size: ${HIKARI_POOL_SIZE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      max-lifetime: ${HIKARI_MAX_LIFETIME}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
  flyway:
    url: ${APP_DB_URL}
    user: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
  jpa:
    open-in-view: false
server:
  port: 8080

logging:
  level:
    root: error
    sql: error
    web: error

