spring:
  application:
    name: student-result-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/srms
    username: srms
    password: secret
    hikari:
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 10000
  flyway:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srms
    out-of-order: true
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      password: secret
      host: localhost
      port: 6379
server:
  port: 8080

